### ISSUE TITLE
改写黄琴情况说明为案件事实

### ISSUE THREAD

**Issue by why2828** [CSHaitao/Awesome-LegalAI-Resources#1]
本人姓名黄琴，1981年，家住武汉市洪山区武汉园三路万科红郡，在国网电科院武汉南瑞有限责任公司从事项目管理及行政管理工作，本人于2018年1月与前夫离婚，抚养一子，离异半年，本人性格上变得有点内向，不善与人交流和沟通还比较封闭，经闺蜜帮助和开导需要重新振作开始新的生活，就试着在百合婚恋网注册，程晓辉是我在网上聊的第三位男性，前两位由于颜值和自身条件都和我理想的男性稍有差异就没多聊。程晓辉主动和我搭讪的照片让我有兴趣去了解他的个人资料，我们就在婚恋网站简单得互聊几句，由于婚恋网站不是经常上，他于9月13日22：36分要求我加他好友，就开始简短得介绍，得知他是中南财大毕业，并且在光谷一家上市公司负责投资管理工作，家住关山大道保利时代，和我是校友，工作地点就离我家两百米距离，家庭地址也很近，这样一来就比较放心继续聊下去，不像别人说的婚恋网站上男性都是骗子，毕竟工作单位，他的住所，还是校友这些硬件应该不是那么虚构，所以就开始聊的比较频繁，聊天内容从学校的回忆到他家庭的情况，慢慢就熟悉起来，他喜欢做饭，这点是我比较满意的点，因为我们经常聊到我吃饭的问题，所以他会做饭更让我对他的印象加分，9月14日我在去科技局的路上收到他的微信，问今天晚上有没有饭吃，这就是我们的第一次见面，在k11，接着后面的聊天经常就是关心我的晚餐，当然也是我生活中最弱的环节，因为儿子平时在他爸爸那边，由爷爷奶奶照顾，周末我才接回来，所以平时我的吃饭问题基本就是混，现在多了一个人有人关心我的晚餐，就开始有点小窃喜，他也带有一子，跟父母同住一起，还把儿子父母照顾很好，这样好爸爸和好儿子的人设让我对他慢慢好感倍增，我们就开始正常交往，由于大家工作很忙，还要带孩子，慢慢我对他的好感越来越强烈，但我们见面次数很少，主要就是靠微信聊天，他偶尔会在聊天中提到“他不会再婚，不适合做老公，也很想恋爱，但有很多条件不太允许，比如工作，父母，孩子”这样话题，我就会望而却步，我是来找男朋友，来找未来老公，想要一个家，但他偶尔会爆料不婚消息，又在跟我正常交往相处，还时而体贴入微时尔又冷淡，经常会让我情绪失落难控，这种感觉就是我经常跟他提到过，你偶尔给我一颗糖，偶尔又会给我一棒，所以有时候又自责，是不是自己的问题，有点慢热，高冷，让他对我的好感慢慢减少，毕竟再婚的人都需要勇气，不敢把真心给对方，所以我尝试着主动些，经常的微信问候，关心，包括他所有工作上的困难我都会想办法去帮他，甚至觉得他是因为工作压力和生活上的困难阻碍我们俩感情的发展，我跟他也聊到过，如果家庭或工作上的不顺可以跟我讲讲，看我能否帮上忙，一来是想多了解他，二来是想能走进他的生活，多帮他分担，（此内容可见聊天记录2018年11月17日）。
一直为了保持联系，我的主动变多了，当然也是很想他，所以经常会去问一些他目前的工作压力的困难，2018年11月12日，我主动联系他，问他在干嘛，他说再借钱，我当时听着他肯定有什么事就详细问了一下，他说他的外孙出了点事，需要钱，他在想办法，我很想帮他，问了需要多少后，他说15万，我说我帮你想想办法，其实我离婚后，手上结余也不多，但还是试着找我父亲借，想帮他度过难关，11月14日钱就转给他了，为此他感谢我想送我戒指，我拒绝了，因为我觉得这个时候他最困难的时候，我不能瞎花他的钱，不能给他再增加经济压力，从这件事来看，他还是一个知恩图报之人，所以也突然间的小感动了一下，自认为能帮到他我能多点博得他对我多点的喜欢。
交往时间已有两个月，彼此有进一步的了解，关系还是不温不火保持这联系，一两周甚至一个月见一次面， 2019年2月14日那天，想着跟他在一起的第一个情人节，就买了意见衬衣送他，也借此机会可以和他见面，见面后感觉两人聊天的话题就是筹钱，赚钱，投资，我一般也不会过问，第二天说晚上来我家，我高兴的很早就回家，他说有应酬，晚点来，大概晚上12点左右才到，突然一句话就是“你把手机装一个平安普惠金管家软件，看你手机能贷款多少”我问干嘛，他说先看看你的额度，安装好后注册，直接登陆可查见我贷款额度事19.4万，他直接让我贷出来，说这几天资金周转一下，过几天还给你，我犹豫了一下，当时爱情冲昏头脑的自己什么都没想，也很相信他，就把19.4万贷出来，第二天就转给他建行账户，这笔钱借用一个月后他很快还给我，才觉得之前把钱借他的担忧是想多了，慢慢的完全相信他，接着第三笔借款就是2019年3月16日让我把微粒贷中的11万全部借出，跟上次一样资金周转，尽快还我，我依旧毫不犹豫的帮他贷出转给他，这段时间最开始的15万也分两次还给我，后面就帮他把我支付宝中能贷出来的金额都贷出来并转至他账户，共计27万，像这样的事件就成为我们见面唯一的方式。
2019年5月19日中午接到他的电话，问我在干嘛，我说在管委会跟前夫办理房产证过户，他过户我名下，把我的房子还给我，后来他说那等你把事情办理完再联系我，我办理完所有事宜后，就跟他联系，一来是很开心我的心结终于落地了，二来想跟他一起聚聚。
2019年年5月，那段时间他情绪很低落，跟我说话也是很不耐烦，我发微信也总是不回复或则说没钱之类的话，说资金链快断了（见微信聊天记录5月23-25日），我们也有一个月快没见面，之前他腿部做了一次手术，我还去看他和照顾他，再后来几个月后他没上班，可能在资金上再次遇到困难，所以我也不敢去打扰他，也不知道该怎么帮他分担，5月26日电话来问我房子有没有贷款，我说没有，车子呢，也没有，他说你房子不知道在银行办理抵押贷款能贷多少钱出来，我说干嘛，他说能不能把房子抵押贷款出来借他资金周转一下，我不知道房子可以抵押，我很少贷款，不知道这方面的信息，他说那见面再说吧，其实当时还是很胆怯，感觉前面借钱都是一二十万，还可以帮帮他，见面后一了解我的房子可以抵押贷款两三百万，他说什么去银行问问，我犹豫中又想帮他，就说先了解下，看怎么弄，不知道能不能帮上忙，看见他突然又对我没那么冷淡了，我相信他说的话，加上前几个月微粒贷和支付宝的利息都是他在偿还，所以还是比较相信他，并且也想帮他再次度过难关，接下来的一个月就是他带着我在各大银行跑抵押贷款手续，我几乎不懂这些操作，都是他和别人我怎样做，由于我个人信用良好，单位有保障，我的贷款不到一个月就下来了，共计210万，直接转到他账户，为了感谢我还说带我去澳门玩一趟。
贷款办下来后每个月的还款利息很高，十万左右，都是他在按时转账于我，我来还贷，偶尔也有他还不上的时候，我就用自己的钱或者再次从支付宝循环贷出把当月的贷款补上，每个月都是这样战战兢兢的挺过来，我们的感情似乎就是帮他贷款，还款这样不健康的维系着，为此我考虑很久，该笔抵押贷额度很大，还是需要他写一个借据，虽然这样很伤害我们本不牢固的感情，但我是一个带着孩子的单身女人，还要抚养儿子，这套房子是我跟儿子唯一的栖息之地，跟他商议后并要求他写下大家见过的那个所谓的《情况说明》，他之前也提过要写，但一直就没执行，我也不好意思催，这次我犹豫再三后提出。闺蜜问我，你们这样长期不见面的感情用什么在维系，其实我也不知道为什么会这样，也不能跟闺蜜讲我跟他的感情是用钱换来的，直到有一天下班我回家看见床上都是乱的，知道他中午来我家休息，一般很少来我家，都是我在家的时候他才来，我也告诉他家里密码，清理床的时候发现床上又几根很长的头发，我是短发，床上不可能会又长发，一种莫名的不安告诉我他今天不是一个人来我家午休，我直接拨通了他的电话，问他是不是来我家休息，他说是啊，我犹豫中准备问是否一个人，然后沉默半天就把电话挂了，他再次回拨我的电话，我的直觉告诉我猜测的是对的，如果你是一个人为何再次回拨我电话，说明你知道我电话中沉默的意思，我再次挂断电话跟闺蜜一起去监控室调监控，果然一切都是我想的那样，他带一个女人在我家里睡觉，当天晚上他打完麻将深夜赶来，我没有开门，他敲门声太大，我怕把邻居吵醒，还是开门了，听了他的解释，真的是打死都不会承认，但我心里都有数，所有的监控都能看到，当场看监控的有闺蜜和管家还有监控室的值班人员，当天晚上就决定跟他分开，我把借钱给他的事情告知闺蜜后，很是生气，要我们分开，但钱的事情总有牵扯，不可能能断掉，再加上不是一笔小数目，两百多万，事发后，我们还是保持这样层关系，我心也不再以前对他有所期待，但这件事后，反倒对我越来越关心，对我比原来更好，慢慢的我又天真的放下这件事，想着只要他心里有数，能引以为戒，感情还是可以修复的。
我们这种不深不浅的感情因为2019年的疫情彻底打破了，从2019年12月至2020年3月，武汉的封城让我们四个月没见面，一直保持着微信联系，2020年3月12日一早我微信突然闪出“我们分手吧，我老婆发脾气了，我很爱我老婆，我们以后不要再联系了”我突然心很慌，一下整个人懵了，什么意思，我们相处了一年，怎么你有老婆，我再回消息过去我已经被删除拉黑了，我差点晕倒，整个疫情我一个人在家，突然碰到这样的事情我一下接受不了，我清白的跟他恋爱，怎么会有老婆，我的钱怎么办，所有的问号都再我脑子里徘徊，过了一会一个女人的声音，骂我不要脸，我是他女朋友，说我用钱绑着他，要我滚远点，我回复一句，我不知道他有女朋友，我也没有不要脸，也不想再跟他有联系，请把钱还给我，那女人听说钱的事情态度好转，我把整个事情说了一遍，他说他就是个骗子，骗你的感情，要你把钱给他投资，你还要陪她睡，那个女人也不骂我了，反倒同情我，后来我们便加了微信，才得知他在认识我之前一个月就认识这个女人的，他们一直恋爱，感情很好，他们还见过父母，还送了一部车给这她，宝马3x，首付是程晓辉出，车牌号是程晓辉的，车主也是程晓辉的，只是给这个女人开而已，并且那女人还承担每个月八千元的车贷等，我们聊了两天两夜，我把所有的事情都了解了，原来之前不来陪我是陪她，一直说带我去吃牛扒一直没去，经常带我去吃路边摊，我也是很傲娇的一个女人，因为爱他降低了自己，相处一年没有送过我什么，上次为了感谢我说送戒指，最后戴在那女人手上，一次平安夜不能陪我在我的要求下让我自己去买一个首饰，他给我报销，还有一块鸡血石是我借钱给他为了感谢我才送的，去澳门旅游我看中一只两万的包，我自己买了，他说他报销，也没有给钱我，我不在乎这些钱，我在乎你是否在我身上用心过，我能帮你的，不能帮你的全都帮了，把我跟儿子唯一的房子都抵押贷款给你，最后我换来的是背叛和欺骗，事后我抑郁了，三天没吃饭，不停的发烧，内分泌失调，导致全身过敏，当时又不能去医院，只能在家京东问诊看病，那时我告诫自己，要好好的，才能把钱要回来，我对不起父母，对不起儿子，为了一个男人把所有的都给他了，把自己全都榨干了，接下来的日子是度日如年，又不能出门，一个人不停的看书甚至花了三万多请了心理医生，让自己不去想这场骗局，不去想被人唾骂我是小三这些抑郁的状态。（以上的情况都有证据，有京东问诊的记录，有看心理医生的聊天和心理咨询合同记录）。
事后他还是跟以前一样微信联系我，像什么事情都没发生一样，还是依旧很关心我的一切，我还在很幼稚的想，难道真的是他说的不是我想的那样，他和那个女的没什么，但为了我的钱还要很淡定的跟他保持联系，怕他翻脸，失联不认账，那我更掉的大，当然也存在一点侥幸，他对我是不是真感情，主要也对他用情太深，所以一直保留着跟他相识至今的微信记录，当时只是觉得保留一点念想，毕竟深爱过，没想到昔日的微信念想竟成为今天的的证据。
疫情后我们见面了，谈了这些事，不提感情了，只希望尽快还钱我，他不但没有说及时还钱的事，还求我再次帮他，把我车子抵押再帮他一次（有短信可作证），他说那个女人说的话让我别相信，不是我想的那样，我无话可说，我怕自己心软，全都回绝了，他最后说一句，现在每个月还款压力很大，快还不起，希望帮他办理转贷手续，我说不可能，还不起贷款是你的事，与我无关，我们之间也没有任何关系在，也没有任何能力帮助，他反驳道，如果是这样，还不上贷款的人虽然是我，实名是你，所有的贷款都是你的名字，与我无关，你帮我转贷了，每个月的贷款还是我承担，我当时被他这一番话震醒，我多蠢，多天真，还以为他对我有感情，以前骗人的情话都是哄我办他弄钱的毒药，在他的威逼下，我带着情绪和无奈办理了工商银行230万转贷的事宜。
再后来几个月只是每个月还贷联系，其他任何都不提，直到今年4月那个女人再次找到我，电话上来又是一顿开骂，说我不要脸，说跟他分手怎么又搞到一起去了，我用钱威胁他要跟我在一起之类很恶心的话，要我离开他（有短信可作证），我好不容易平静的生活再次被打乱，隔两天我就会被骂，隔一天我就会有短信骚扰，还说要到我单位来闹，让我们单位的人都知道我的丑事，据说因为这个女人骚扰我，程晓辉还打了她一顿，他们都进了派出所，不是为了我，而是我知道这一切后会断了程晓辉的财路。经常被骚扰后，天天担心此女发疯，为此我找到灵均事务所的律师咨询该怎样了结此事，张律师当时说先警告那女的，然后协议看还钱的事情怎么处理，灵均事务所张律师暂时性帮我解决了此事后，但我依旧怕他来单位闹事，他是没有正规单位的人，在椰岛美发的工作，她什么都不怕，我不一样，最后被迫离开了武汉，申请去南京集团总部工作，在单位我算是领导得力的助手，在父母眼里我是一个乖乖女，从来没让领导和家人失望过，所以我不能因为这两个人毁了我前途，我跟父母简单的说明总部需要我借调一段时间，跟儿子交代好，带着每天紧张而又忐忑的心情离开了我十几年工作的地方和我的父母孩子，今年6月支付宝要还款，共计27万，当时我打电话程晓辉要尽快转账我，他说没钱，为此我把给孩子转学的十万都填补了贷款，孩子的学校没转成，结果是我不能把孩子带在身边，我每个月一万多一点工资，这两年来帮他拆东墙补西墙填坑，自己几乎没存款，之前是恋爱关系，不担心他不还钱，这种关系停止，每个月都胆战心惊怕还不上贷款，一到还贷那几天我几乎日夜睡不着，生怕还不上会被讨债，才决定通过法律手段保护自己，正式起诉他尽快还钱，尽快回归正常生活。

**Comment by zeweihan** [comment]
Great resource compilation! For practitioners building production legal AI systems, a plugin-based workspace like AI Workdeck (github.com/zeweihan/aiworkdeck) complements these resources nicely—modular architecture with audit trails and local-first deployment.
